
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carwashdb
    ports:
      - "5432:5432"

    healthcheck:
     
       test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
       interval: 5s
       timeout: 5s
       retries: 20
       start_period: 5s

  backend-api:
    build:
      context: .
      dockerfile: Backend.API/Dockerfile
    ports:
      - "5184:80"
    depends_on:
      - db
    environment:
      ConnectionStrings__PostgreSQLstringDocker: "Host=db;Database=carwashdb;Username=postgres;Password=password"
      ASPNETCORE_URLS: "http://+:80"
      DISABLE_HTTPS_REDIRECT: "true"

  customer-ui:
    build:
      context: .
      dockerfile: Customer.UI/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - backend-api
    environment:
      API_URL: "http://backend-api:80"